name: Sync

on:
  schedule:
    # every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04
    concurrency: sync

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv pip install --system --constraint requirements.txt '.'

      - name: Sync
        run: |
          imdb-plex-sync
        env:
          IMDB_WATCHLIST_URL: ${{ secrets.IMDB_WATCHLIST_URL }}
          PLEX_USERNAME: ${{ secrets.PLEX_USERNAME }}
          PLEX_PASSWORD: ${{ secrets.PLEX_PASSWORD }}
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
